### PR TITLE
Reimplement license management and allow multiple platforms

### PR DESCRIPTION
**Pull request by webbertakken**
This PR will take care of three things:

- Reimplement license activation as part of this action
- Also implement returning of license as part of this action
- Effectively allow multiple Unity versions and platforms

### CODE REVIEW

**Comment by webbertakken** [comment]
@GabLeRoux how to determine which build requires which of your images?

Supported platforms by unity ([source](https://docs.unity3d.com/ScriptReference/BuildTarget.html)):
    
- `StandaloneOSX` # Build a macOS standalone (Intel 64-bit).
- `StandaloneWindows` # Build a Windows standalone.
- `StandaloneWindows64` # Build a Windows 64-bit standalone.
- `StandaloneLinux64` # Build a Linux 64-bit standalone.
- `iOS` # Build an iOS player.
- `Android` # Build an Android .apk standalone app.
- `WebGL` # WebGL.
- `WSAPlayer` # Build an Windows Store Apps player.
- `PS4` # Build a PS4 Standalone.
- `XboxOne` # Build a Xbox One Standalone.
- `tvOS` # Build to Apple's tvOS platform.
- `Switch` # Build a Nintendo Switch player.

Is there a source or logical way how to determine when to use which of your images?

- `-android`
- `-facebook`
- `-ios`
- `-mac`
- `-webgl`
- `-windows`

Currently I've implemented a [mapping](https://github.com/webbertakken/unity-builder/blob/v0.4/src/model/image-tag.js#L44) that does this for the end user. The mapping needs to be updated and mapped correctly. For that I'm looking for a source of truth.

Any ideas?

**Comment by GabLeRoux** [comment]
I'd say the mapping is the right solution. Since the docker image is linux based, there are many platforms that can't be supported. ie; switch, XboxOne, PS4, WSAPlayer.

On my side, there no source of truth other than the following code:
https://gitlab.com/gableroux/unity3d/blob/5bdeca28/ci-generator/src/gitlab_ci_generator.py#L83

I did not use exact names from components as some of them required a combination of components to work (example: `"mac": {"components": "Mac,Mac-Mono"}`). Even worse then that, some older unity versions used different component names so I had to figure out a way to allow overriding it. Example here:
https://gitlab.com/gableroux/unity3d/blob/4249522f/ci-generator/unity_versions.old.yml#L1145-1150

So specifying it in the code like you did seems like the way to go at least for the available docker images.

Microsoft with their powershell module did something here:
https://github.com/microsoft/unitysetup.powershell/blob/6af6dfd/UnitySetup/UnitySetup.psm1#L6

They also seem to have a way to know which components are currently available for a given unity version. I did not go into more details, but you can see a few examples in the readme:
https://github.com/microsoft/unitysetup.powershell

Hope it helps and thanks for all these efforts. I wish I had more spare time to help you a little more 👍 I'll keep following your development :)

**Comment by webbertakken** [comment]
Pretty solid information sources! Thanks for that. I had not seen the microsoft implementation before.

> I wish I had more spare time to help you a little more 👍 I'll keep following your development :)

Thanks again! I really appreciate your support. I'll do what I can; I too wish for more spare time 😉

**Comment by webbertakken** [comment]
Error may be related to beta features that are in the the `test-project`

Error given for `Actions 😎 / Build for StandaloneWindows on version 2019.2.11f1` job

```console
BuildFailedException: Burst compiler (1.1.2) failed running

stdout:
An unexpected exception occurred: 
stderr:
Error while executing command: /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/.Runtime/hostlin/vswhere.exe -legacy -latest -format value  -property installationPath
System.InvalidOperationException: Error while executing command: /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/.Runtime/hostlin/vswhere.exe -legacy -latest -format value  -property installationPath ---> System.ComponentModel.Win32Exception: ApplicationName='/github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/.Runtime/hostlin/vswhere.exe', CommandLine='-legacy -latest -format value  -property installationPath', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <fb35542c49c94f4d9bf912c73e79fe13>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <fb35542c49c94f4d9bf912c73e79fe13>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at Burst.Compiler.IL.Helpers.ProcessHelper.Run (System.String exePath, System.String arguments, System.String workingDirectory, System.IO.TextWriter consoleOut, System.IO.TextWriter consoleErr) [0x000a7] in <3179d4839c86430ca331f2949f40ede5>:0 
   --- End of inner exception stack trace ---
  at Burst.Compiler.IL.Helpers.ProcessHelper.Run (System.String exePath, System.String arguments, System.String workingDirectory, System.IO.TextWriter consoleOut, System.IO.TextWriter consoleErr) [0x000f5] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Helpers.ProcessHelper.RunNative (System.String exePath, System.String arguments, System.String workingDirectory, System.IO.TextWriter consoleOut, System.IO.TextWriter consoleErr) [0x00000] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Aot.AotHelpersMSVC.GetMSVCBaseAndMajorVersion (System.Int32 explicitVersionOrZeroForLatest, System.Int32& majorVersion) [0x00069] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Aot.AotHelpersMSVC.GetMSVCToolsPath (Burst.Backend.TargetCpu cpu, System.Int32 explicitVersionOrZeroForLatest) [0x00002] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Aot.AotNativeLinkMSVCBase.ValidateExternalToolChain (Burst.Backend.TargetCpu targetCpu) [0x00000] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Aot.AotNativeLink.ValidateExternalToolChain (Burst.Compiler.IL.Aot.AotCompilerOptions options) [0x0007a] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Compiler.IL.Aot.AotCompiler.Link (System.Collections.Generic.List`1[T] groups, Burst.Compiler.IL.Aot.AotCompilerOptions compilerOptions) [0x00160] in <3179d4839c86430ca331f2949f40ede5>:0 
  at Burst.Bcl.BclApp.CompileAndLink (System.Collections.Generic.List`1[T] methodGroups) [0x000e4] in <ea0e858b503c4141a1b11a11b90523bb>:0 
  at Burst.Bcl.Program.Main (System.String[] args) [0x00176] in <ea0e858b503c4141a1b11a11b90523bb>:0 
at Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunProgram (UnityEditor.Utils.Program p, System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, UnityEditor.Build.Reporting.BuildReport report) [0x001f4] in /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/Editor/BurstAotCompiler.cs:659 
  at Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunManagedProgram (System.String exe, System.String args, System.String workingDirectory, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, UnityEditor.Build.Reporting.BuildReport report) [0x0004d] in /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/Editor/BurstAotCompiler.cs:597 
  at Unity.Burst.Editor.BurstAotCompiler+BclRunner.RunManagedProgram (System.String exe, System.String args, UnityEditor.Scripting.Compilers.CompilerOutputParserBase parser, UnityEditor.Build.Reporting.BuildReport report) [0x00001] in /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/Editor/BurstAotCompiler.cs:571 
  at Unity.Burst.Editor.BurstAotCompiler.OnPostBuildPlayerScriptDLLsImpl (UnityEditor.Build.Reporting.BuildReport report) [0x006c6] in /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/Editor/BurstAotCompiler.cs:286 
  at Unity.Burst.Editor.BurstAotCompiler.OnPostBuildPlayerScriptDLLs (UnityEditor.Build.Reporting.BuildReport report) [0x0000e] in /github/workspace/test-project/Library/PackageCache/com.unity.burst@1.1.2/Editor/BurstAotCompiler.cs:46 
  at UnityEditor.Build.BuildPipelineInterfaces.OnPostBuildPlayerScriptDLLs (UnityEditor.Build.Reporting.BuildReport report) [0x00033] in /home/builduser/buildslave/unity/build/Editor/Mono/BuildPipeline/BuildPipelineInterfaces.cs:452
```

Will investigate later

**Comment by webbertakken** [comment]
The above (5 commits) allows for the default-build-script files to be edited in the context of unity settings and deps.

The 4 before it focus on building a simple project, rather than bleeding edge ECS technology.

**Comment by DanVicarel** [comment]
Just throwin this out there... there is now Powershell Core, which runs on Linux. So @GabLeRoux if that Microsoft ps script seems more stable or future proof, u could possibly use it in ur own images. Not sure how much reinventing the wheel that would involve...

**Comment by GabLeRoux** [comment]
Maybe worth trying, but [Unity powershell module](https://github.com/microsoft/unitysetup.powershell) is definitely only compatible for Windows as of today. It would probably make sens to use it to create windows images (I don't think docker would be handy here tho, I'm more thinking of AWS AMIs for example).

**Pull request merged**
