### PR TITLE
Add Android Build Settings and macOS buildNumber

### PR DESCRIPTION
**Pull request by davidmfinol**
Adds parameters for Android for #34:
-androidAppBundle 
-androidKeystoreName
-androidKeystoreBase64
-androidKeystorePass
-androidKeyalias
-androidKeyaliasPass

Need to update PlayerSettings.macOS.buildNumber for each submission to the Mac App Store. Per [Unity ](https://docs.unity3d.com/Manual/HOWTO-PortToAppleMacStore.html) and [Apple ](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364) documentation, just applying the auto-generated version makes the most sense.

### CODE REVIEW

**Comment by davidmfinol** [comment]
@webbertakken 
I think the Tests check failed only because of some transient problem? At the least, I don't see a problem with the tests themselves.

I do have another problem with this PR, though. I'm currently getting an error when submitting to the Mac App Store: 
[Transporter Error Output]: ERROR ITMS-90061: "This bundle is invalid. The value for key CFBundleVersion [1.30.6] in the Info.plist file must contain a higher version than that of the previously uploaded version [38]. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"

My build number is currently at 38 since I had been manually incrementing the number by 1, similar to what I had been doing for the Android releases (a mistake, in hindsight). 
I can't use the the androidVersionCode: Apple will interpret that number as the first number for CFBundleVersion, which is limited to 4 digits, while the androidVersionCode takes 7 digits with how we currently have it. 

This PR may not be the appropriate place to ask, but I figured I'd ask for any suggestion on what I should do?

**Comment by webbertakken** [comment]
See contribution [guide](https://github.com/webbertakken/unity-builder/blob/master/CONTRIBUTING.md).

Specifically this part:
> Please note that commit hooks will run automatically to perform some tasks;
>
> - format your code
> - run tests
> - build distributable files

The test fails because the distributable file is not automatically generated. Did the pre-commit hook fail?

**Comment by davidmfinol** [comment]
Pre-commit hook ran fine for me.

I just re-ran yarn build again, and I'm not seeing an error: 
image

**Comment by webbertakken** [comment]
Right. It was actually yarn getting a 502. I reran the tests and now they are green.

**Comment by mastef** [comment]
@davidmfinol could `androidCreateSymbolsZip` be implemented in the same way?

**Comment by davidmfinol** [comment]
Yeah, I think you should be able to raise a PR for it.
I think you would need to add `androidCreateSymbolsZip` to `action.yml`, `input.ts`, `build-parameters.ts`, `docker.ts`, `build.sh`, and `AndroidSettings.cs`.
We'd also want to add it to [the documentation](https://github.com/game-ci/documentation/blob/main/docs/github/v2/04-builder.md).


I actually wonder if there is a better approach that would easily enable us to set all of the [EditorUserBuildSettings](https://docs.unity3d.com/ScriptReference/EditorUserBuildSettings.html) through our default build script. That's probably a question for another time, though.

**Comment by mastef** [comment]
@davidmfinol how about this : 

```diff
      - uses: game-ci/unity-builder@v2.0-alpha-6
        name: Build unity project to Android
        with:
           unityVersion: ${{ matrix.unityVersion }}
           targetPlatform: ${{ matrix.targetPlatform }}
           buildsPath: build-${{ matrix.targetPlatform }}
           buildName: ${{ secrets.BUILD_NAME }}
           versioning: Custom
           version: ${{ steps.versionstep.outputs.buildVersion }}
           androidVersionCode: ${{ steps.versionstep.outputs.buildNumber }}
           androidAppBundle: true
           androidKeystoreName: ${{ secrets.ANDROID_KEYSTORE_NAME }}
           androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
           androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
           androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
           androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
+          customParameters: -androidCreateSymbolsZip
```

**Comment by davidmfinol** [comment]
You can do it that way if you want to quicker solution for your project. You would also need a custom `buildMethod` that applies `EditorUserBuildSettings.androidCreateSymbolsZip = true;`

**Comment by mastef** [comment]
> You can do it that way if you want to quicker solution for your project. You would also need a custom `buildMethod` that applies `EditorUserBuildSettings.androidCreateSymbolsZip = true;`

Somebody else also tried with that setting and no success https://answers.unity.com/questions/1767637/batchmode-command-not-generating-symbolszip-file.html?childToView=1822466#answer-1822466 but maybe they didn't add the setting in the cli.

So @davidmfinol you're saying both settings are required? The `EditorUserBuildSettings.androidCreateSymbolsZip = true` and additionally the `-androidCreateSymbolsZip` flag in the CLI? That could be a solution to his problem then as well

**Comment by davidmfinol** [comment]
Passing `-androidCreateSymbolsZip` in the CLI could be useful to check if that flag was passed in your build script, but it's not necessary.

My understanding is that only `EditorUserBuildSettings.androidCreateSymbolsZip = true` is required, so I'm not sure why it didn't work for him.

**Comment by mastef** [comment]
> Passing `-androidCreateSymbolsZip` in the CLI could be useful to check if that flag was passed in your build script, but it's not necessary.
> 
> My understanding is that only `EditorUserBuildSettings.androidCreateSymbolsZip = true` is required, so I'm not sure why it didn't work for him.

Because for me - passing it in the CLI - is also not sufficient. There may be a bigger issue at play here :|

**Pull request merged**
